# Generated by Django 3.2.23 on 2023-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231126_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='blog/defualt.jpg', upload_to='blog/'),
        ),
    ]
