# Generated by Django 3.2.23 on 2023-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
