# Generated by Django 5.0 on 2023-12-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
    ]
